<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Erp.BuildingBlocks.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Erp.SharedKernel\Erp.SharedKernel.csproj" />
    <ProjectReference Include="..\Erp.BuildingBlocks.Infrastructure\Erp.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Catalog\Erp.Catalog.Contracts\Erp.Catalog.Contracts.csproj" />
  </ItemGroup>
</Project>
