<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ERP.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\ERP.Core\ERP.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="ERP.Core.Models.Shared" />
    <Using Include="ERP.Core.Models.Accounting" />
    <Using Include="ERP.Core.Models.CarShowroom" />
    <Using Include="ERP.Core.Models.POS" />
    <Using Include="ERP.Core.DTOs.Shared" />
    <Using Include="ERP.Core.DTOs.Accounting" />
    <Using Include="ERP.Core.DTOs.CarShowroom" />
    <Using Include="ERP.Core.DTOs.POS" />
    <Using Include="ERP.Core.Contracts.Shared" />
    <Using Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
