<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Erp.Migrator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Erp.Composition\Erp.Composition.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
