<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ERP.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ERP.Service\ERP.Service.csproj" />
    <ProjectReference Include="..\ERP.Core\ERP.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="ERP.Core.Models.Shared" />
    <Using Include="ERP.Core.Models.Accounting" />
    <Using Include="ERP.Core.Models.CarShowroom" />
    <Using Include="ERP.Core.Models.POS" />
    <Using Include="ERP.Core.DTOs.Shared" />
    <Using Include="ERP.Core.DTOs.Accounting" />
    <Using Include="ERP.Core.DTOs.CarShowroom" />
    <Using Include="ERP.Core.DTOs.POS" />
    <Using Include="ERP.Core.Contracts.Shared" />
  </ItemGroup>
</Project>
