<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Erp.Modules.Inventory</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Erp.Modules.Inventory.Contracts\Erp.Modules.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Finance\Accounting\Erp.Modules.Accounting.Contracts\Erp.Modules.Accounting.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Platform\Organization\Erp.Modules.Organization.Contracts\Erp.Modules.Organization.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Platform\Settings\Erp.Modules.Settings.Contracts\Erp.Modules.Settings.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Erp.BuildingBlocks.Infrastructure\Erp.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Erp.BuildingBlocks.Web\Erp.BuildingBlocks.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Erp.IntegrationTests" />
    <InternalsVisibleTo Include="Erp.ArchitectureTests" />
  </ItemGroup>
</Project>
